name: Brickblock CI Workflow
on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1

  lint:
    name: Run all linters
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: "yarn lint"

  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./action-a
        env:
          MY_NAME: "Chapati"
