name: Brickblock CI Workflow
on: push

jobs:
  healthcheck:
    name: Setup, Lint, and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./action-a
        env:
          MY_NAME: "Chapati"
